name: geo-function

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install Dependencies
        run: |
            cd functions
            yarn install --frozen-lockfile
      - name: Lint
        run: |
            cd functions
            yarn lint

  auto-deploy:
    runs-on: ubuntu-latest 
    needs: [static-analysis]
    if: github.ref == 'refs/heads/main'
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Install Dependencies 
        run: |
            cd functions
            yarn install --frozen-lockfile
      # - name: Deploying to Firebase 
      #   run: yarn deploy --token $token 
      #   env: 
      #     token: ${{ secrets.FIREBASE_TOKEN }}   
